config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :trips do
    resources :tasks
    resources :participants, only: [ :new, :create, :edit, :update ]
  end

  resources :tasks do
    resources :attachments, only: [ :create, :destroy ]
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :attachments, through: :tasks, dependent: :destroy
  has_many :participants, dependent: :destroy
  accepts_nested_attributes_for :participants
  mount_uploader :photo, PhotoUploader

  # geocoded_by :destination
  # after_validation :geocode, if: :will_save_change_to_address?

  after_create :assign_self_as_participant

  validates :name, presence: true
  validates :destination, presence: true

  def uniq_particpants
    self.participants.select('DISTINCT ON (participants.user_id) participants.user_id, participants.status, participants.id, participants.trip_id').where.not(user_id: nil)
  end

  private

  def assign_self_as_participant
    owner = Participant.new(email: self.user.email, trip: self, status: "joined")
    owner.user = self.user
    owner.save
  end
end

app/controllers/trips_controller.rb
  class TripsController < ApplicationController
  # before_action :set_trip, only: [:show, :edit, :destroy, :update]

  def index
    @trips = Trip.where(user: current_user)
  end

  def show
  end

  def new
    @trip = Trip.new
    @participant = Participant.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    if @trip.save
      entries = params["emails"]
      entries.each do |email|
        unless email == ""
          part = Participant.new(email: email, trip: @trip, status: "incomplete")
          part.save
        end
      end
      redirect_to trip_tasks_path(@trip)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @trip.update(trip_params)
    redirect_to trip_path(@trip)
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.attachments.destroy_all
    @trip.tasks.destroy_all
    @trip.participants.destroy_all
    @trip.destroy
    redirect_to trips_path
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :destination, :start_date, :end_date, :photo)
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end
end

app/views/trips/index.html.erb
<!-- index.html.erb -->

<!-- navbar -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
<i class="fa fa-map-marked-alt"></i>
  <% end %>


  <h2 class="navbar-dash-title">My Dashboard</h2>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="button-create">
        <%= button_to "Create a Trip", new_trip_path, :method => "get", class: "btn-flat-create" %>
      </li>
      <li class="nav-item dropdown">
      <% if current_user.facebook_picture_url %>
        <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
        <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <%= cl_image_tag current_user.photo, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>





<!-- <div class="container"> -->

  <div class="trip-index-container">
    <div class="trip-card-box">
      <h2>My Trips</h2>
      <div class="trip-index-cards">
        <% @trips.each do |trip| %>
          <%= link_to trip_tasks_path(trip) do %>
          <div class="product-card">
            <div class="product-tumb">
              <%= cl_image_tag(trip.photo, crop: :fill) %>
              <%= link_to trip_path(trip), method: :delete, data: { confirm: "Are you sure?" } do %>
              <i class="fas fa-times remove-trip"></i>
              <% end %>
            </div>
            <div class="product-details">
                <h4><%= link_to trip.name, trip_tasks_path(trip) %></h4>
                <p><%= trip.destination %></p>
                <div class="product-bottom-details product-price"><ul style="padding-left: 0;">
                  <% trip.uniq_particpants.each do |participant| %>
                  <li class="avatar-inline" data-toggle="tooltip" data-placement="bottom" title=<%= participant.user.name if !participant.user.nil?  %>><%= cl_image_tag participant.user.photo, crop: :fill, class: "avatar-tiny" if !participant.user.nil? %></li>
                  <% end %>
                </ul>
              </div>
         <!--        <div class="product-links">
                    <a href=""><i class="fa fa-trash-alt"></i></a>
                    <i class="fal fa-trash-alt"></i>
                    <a href=""><i class="fa fa-shopping-cart"></i></a>
                </div> -->
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>



    <div class="personal-tasks-container">
      <h2>My Tasks</h2>
      <div class="task-box-trip">
      <% content_item = current_user.tasks.order('due_date asc') %>
      <% content_item.each do |task| %>
        <%= link_to trip_tasks_path(task.trip) do %>
        <ul class="personal-task">
          <li class="personal-task-content">
            <h4><%= task.name %></h4>
            <div class="task-name-deadline">
             <p>
              <%= task.trip.name %>
            </p>
            <p class="deadline-list">
              <% if task.due_date%>
             Deadline: <%= task.due_date.to_date.strftime('%m/%d') %>
              <% end %>
            </p>
            </div>
          </li>
       </ul>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
  <!-- </div> -->


<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>




<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

app/views/trips/new.html.erb
<!-- navbar -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
<i class="fa fa-map-marked-alt"></i>
  <% end %>


  <h2 class="navbar-dash-title">Create Your Trip</h2>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="dash-link">
        <%= link_to "Back to dashboard", trips_path, :method => "get" %>
      </li>
      <li class="nav-item dropdown">
      <% if current_user.facebook_picture_url %>
        <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
        <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
      <% else %>
        <%= cl_image_tag current_user.photo, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>



<div class="main-wrapper">


<div class="container main-block">
  <div class="row">
<!--    <div class="col-xs-12 col-sm-6 col-md-4"> -->


<div class="create-trip-first col-md-4">

  <%= simple_form_for @trip do |f| %>
    <%= f.input :name, required: true, autofocus: true, input_html: { class: "form-control form-control-lg", placeholder: "Name your trip" } %>
    <%= f.input :destination, input_html: {id: "input-map", type: "serch", name: "trip[destination]", class: "form-control form-control-lg", placeholder: "Where are we going?"} %>
    <%= f.input :start_date, as: :string, required: true, input_html: {class: "datepicker form-control-lg", placeholder: "Pick start date"} %>
    <%= f.input :end_date, as: :string, required: true, input_html: {class: "datepicker form-control-lg", placeholder: "Pick end date"} %>

    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>

</div>

<div class="create-trip-second col-md-4">






<!-- MAP DIV -->

<p>Check out the map</p>

<div id="map-example-container"></div>


<script src="https://cdn.jsdelivr.net/npm/places.js@1.16.1"></script>
<script>

  (function() {
  var placesAutocomplete = places({
    appId: '<%= ENV["ALGOLIA_SEARCH_APP_ID"] %>',
    apiKey: '<%= ENV["ALGOLIA_SEARCH_API_KEY"] %>',
    container: document.querySelector('#input-map')
  });

  var map = L.map('map-example-container', {
    scrollWheelZoom: false,
    zoomControl: false
  });

  var osmLayer = new L.TileLayer(
    'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      minZoom: 1,
      maxZoom: 13,
      attribution: 'Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors'
    }
  );

  var markers = [];

  map.setView(new L.LatLng(0, 0), 1);
  map.addLayer(osmLayer);

  placesAutocomplete.on('suggestions', handleOnSuggestions);
  placesAutocomplete.on('cursorchanged', handleOnCursorchanged);
  placesAutocomplete.on('change', handleOnChange);
  placesAutocomplete.on('clear', handleOnClear);

  function handleOnSuggestions(e) {
    markers.forEach(removeMarker);
    markers = [];

    if (e.suggestions.length === 0) {
      map.setView(new L.LatLng(0, 0), 1);
      return;
    }

    e.suggestions.forEach(addMarker);
    findBestZoom();
  }

  function handleOnChange(e) {
    markers
      .forEach(function(marker, markerIndex) {
        if (markerIndex === e.suggestionIndex) {
          markers = [marker];
          marker.setOpacity(1);
          findBestZoom();
        } else {
          removeMarker(marker);
        }
      });
  }

  function handleOnClear() {
    map.setView(new L.LatLng(0, 0), 1);
    markers.forEach(removeMarker);
  }

  function handleOnCursorchanged(e) {
    markers
      .forEach(function(marker, markerIndex) {
        if (markerIndex === e.suggestionIndex) {
          marker.setOpacity(1);
          marker.setZIndexOffset(1000);
        } else {
          marker.setZIndexOffset(0);
          marker.setOpacity(0.5);
        }
      });
  }

  function addMarker(suggestion) {
    var marker = L.marker(suggestion.latlng, {opacity: .4});
    marker.addTo(map);
    markers.push(marker);
  }

  function removeMarker(marker) {
    map.removeLayer(marker);
  }

  function findBestZoom() {
    var featureGroup = L.featureGroup(markers);
    map.fitBounds(featureGroup.getBounds().pad(0.5), {animate: false});
  }
})();
</script>
<!-- END OF MAP DIV -->

</div>

<div class="create-trip-third col-md-4">

  <p>Invite your friends <!-- <i class="material-icons">add_circle_outline
</i> --></p>
  <%# 10.times do |i| %>
  <ul id="invite-friends">
    <li><%= text_field_tag 'emails[]', nil, class: 'special_input', placeholder: "Enter an email of your friend" %></li>
    <li><%= text_field_tag 'emails[]', nil, class: 'special_input', placeholder: "Enter an email of your friend" %></li>
    <li><%= text_field_tag 'emails[]', nil, class: 'special_input', placeholder: "Enter an email of your friend" %></li>
    <li><%= text_field_tag 'emails[]', nil, class: 'special_input', placeholder: "Enter an email of your friend" %></li>
    <li><%= text_field_tag 'emails[]', nil, class: 'special_input', placeholder: "Enter an email of your friend" %></li>
  </ul>
  <%# end %>
  <%= f.submit "Create trip", class: "btn btn-create btn-lg" %>
  <% end %>
</div>

</div>








      </div>
    </div>

  </div>
</div>
</div>