config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :trips do
    resources :tasks
    resources :participants, only: [ :new, :create, :edit, :update ]
  end

  resources :tasks do
    resources :attachments, only: [ :create, :destroy ]
  end
end

app/views/pages/home.html.erb
<!-- BANNER -->

<div class="banner">
  <div class="banner-main-header">
    <h1 class="main-header">
      Holy Trip
    </h1>
  </div>
  <div class="banner-typed-header" id="typed-strings">
      <p>With HolyTrip you <strong>can organize a trip</strong></p>
      <p>With HolyTrip you <strong>can invite friends</strong></p>
      <p>With HolyTrip you <strong>can delegate tasks</strong></p>
      <p>With HolyTrip you <strong>can share attachments</strong></p>
      <p>With HolyTrip you <strong>are always on the same page</strong></p>
  </div>
  <span id="typed"></span>
</div>

<%= button_to "Start now", trips_path, :method => "get", class: "btn-banner" %>

<div class="secondary-header">
  <h3>How it works</h3>

</div>

<!-- MAIN CONTENTS -->
<div class="home-content home-content-up">
  <div class="content">
    <h1 class="content-text">Plan your trip</h1>
      <p><i class="far fa-check-circle fa-sm"></i> Choose a destination</p>
      <p><i class="far fa-check-circle fa-sm"></i> Pick your dates</p>
      <p><i class="far fa-check-circle fa-sm"></i> Add your friends</p>
  </div>
  <div class="content-img">
    <%= image_tag("create-trip.png", alt: "Create Trip") %>
  </div>
</div>
<div class="home-content home-content-down">
  <div class="content-img">
    <%= image_tag("Task-Manager.png", alt: "Task Manager") %>
  </div>
  <div class="content">
    <h1 class="content-text">Relax</h1>
    <p><i class="far fa-check-circle fa-sm"></i> Create tasks</p>
    <p><i class="far fa-check-circle fa-sm"></i> Organize your trip</p>
    <p><i class="far fa-check-circle fa-sm"></i> Share responsibilities</p>
  </div>
</div>
<!-- footer -->

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>


<script>
  var typed = new Typed('#typed', {
    stringsElement: '#typed-strings',
    loop: true,
    typeSpeed: 55,
    smartBackspace: true,
    cursorChar: '',
  });
</script>